// PI V1 release-candidate deployment marker: keep the customer worker deployment tied to this release train.
// Launch-gate repair: single-primary edge inference, gateway routing, sequential fallbacks.
import { deterministicFallback } from './deterministic-fallback.mjs';

const ALLOWED_ORIGIN = 'https://pisolutions9.github.io';
const MAX_INPUT = 8000;
const MAX_OUTPUT_TOKENS = 500;
const PROVIDER_TIMEOUT_MS = 5000;
const EDGE_TIMEOUT_MS = 12000;
const DEFAULT_EDGE_MODEL = '@cf/meta/llama-3.1-8b-instruct-fast';
const EDGE_ALTERNATIVE_MODEL = '@cf/meta/llama-3.1-8b-instruct';
const EDGE_THIRD_MODEL = '@cf/meta/llama-3.1-8b-instruct-fp8';
const OPENAI_MODEL_FALLBACKS = ['gpt-5.6-luna', 'gpt-5.6-terra', 'gpt-5.6-sol', 'gpt-5'];
const PI_INSTRUCTIONS = "You are PI, an autonomous intelligence assistant coordinated by Krishna. Answer the user's actual question directly and naturally. Do not expose internal routing, classification, planning, tool, or verification language. If current facts or an external action cannot be verified, say what is missing instead of inventing it. Never claim an action was completed unless it actually was.";

function corsHeaders(origin) {
  return {'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...(origin===ALLOWED_ORIGIN?{'access-control-allow-origin':ALLOWED_ORIGIN}:{}),'access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type','access-control-max-age':'600',vary:'Origin'};
}
function json(body,status,request,extraHeaders={}){const origin=request.headers.get('Origin')||'';return new Response(JSON.stringify(body),{status,headers:{...corsHeaders(origin),...extraHeaders}});}
function preflight(request){const origin=request.headers.get('Origin')||'';if(origin&&origin!==ALLOWED_ORIGIN)return json({ok:false,error:'origin_not_allowed'},403,request);return new Response(null,{status:204,headers:corsHeaders(origin)});}
function providerError(response){if(response.status===401)return{error:'chat_provider_auth_failed',status:502};if(response.status===403)return{error:'chat_provider_access_denied',status:502};if(response.status===404)return{error:'chat_provider_model_or_endpoint_not_found',status:502};if(response.status===429)return{error:'chat_provider_rate_limited',status:503};if(response.status>=500)return{error:'chat_provider_server_error',status:503};if(response.status>=400)return{error:'chat_provider_request_rejected',status:502};return{error:'chat_provider_unavailable',status:503};}
function rateLimitHeaders(response){const headers={};for(const name of['x-ratelimit-limit-requests','x-ratelimit-remaining-requests','x-ratelimit-reset-requests']){const value=response.headers.get(name);if(value)headers[name]=value;}return headers;}
async function callProvider({apiKey,model,baseUrl,message}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),PROVIDER_TIMEOUT_MS);try{return await fetch(`${baseUrl.replace(/\/$/,'')}/responses`,{method:'POST',headers:{authorization:`Bearer ${apiKey}`,'content-type':'application/json'},body:JSON.stringify({model,store:false,max_output_tokens:MAX_OUTPUT_TOKENS,instructions:PI_INSTRUCTIONS,input:message}),signal:controller.signal});}finally{clearTimeout(timer);}}
function extractAnswer(body){return body?.output_text?.trim()||body?.output?.flatMap(item=>item?.content||[]).find(part=>part?.type==='output_text')?.text?.trim();}
function extractEdgeAnswer(result){if(typeof result==='string')return result.trim()||null;const candidates=[result?.response,result?.output_text,result?.result?.response,result?.result?.output_text,result?.choices?.[0]?.message?.content];for(const value of candidates){if(typeof value==='string'&&value.trim())return value.trim();if(Array.isArray(value)){const text=value.map(part=>typeof part==='string'?part:(part?.text||part?.content||'')).join('').trim();if(text)return text;}}return null;}
async function runEdgeWithTimeout(env,model,message){const input={messages:[{role:'system',content:PI_INSTRUCTIONS},{role:'user',content:message}],max_tokens:MAX_OUTPUT_TOKENS};const work=env.AI.run(model,input,{gateway:{id:'default',skipCache:true}});const timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error(`edge model timeout: ${model}`)),EDGE_TIMEOUT_MS));return Promise.race([work,timeout]);}
async function callWorkersAI(env,message){if(!env.AI||typeof env.AI.run!=='function')return null;const configured=env.PI_EDGE_MODEL||DEFAULT_EDGE_MODEL;const models=[...new Set([configured,EDGE_ALTERNATIVE_MODEL,EDGE_THIRD_MODEL])];for(const model of models){try{const result=await runEdgeWithTimeout(env,model,message);const answer=extractEdgeAnswer(result);if(answer)return answer;console.error(`Workers AI empty response: ${model}`);}catch(error){console.error(`Workers AI model failed: ${model}`,error instanceof Error?error.message:String(error));}}return null;}
function recoveryResponse(message,request,failure){const answer=deterministicFallback(message);if(!answer)return null;const headers=failure?.response&&failure.failure.error==='chat_provider_rate_limited'?rateLimitHeaders(failure.response):{};return json({ok:true,answer,source:'pi-chat-deterministic-recovery',truth:'deterministic',providerFailure:failure?.failure?.error||'chat_provider_unavailable'},200,request,headers);}
export default{async fetch(request,env){const url=new URL(request.url);const origin=request.headers.get('Origin')||'';if(url.pathname!=='/api/chat')return new Response('Not found',{status:404});if(origin&&origin!==ALLOWED_ORIGIN)return json({ok:false,error:'origin_not_allowed'},403,request);if(request.method==='OPTIONS')return preflight(request);if(request.method!=='POST')return json({ok:false,error:'method_not_allowed'},405,request);let payload;try{payload=await request.json();}catch{return json({ok:false,error:'invalid_json'},400,request);}const message=String(payload?.message||'').trim();if(!message)return json({ok:false,error:'message_required'},400,request);if(message.length>MAX_INPUT)return json({ok:false,error:'message_too_large'},413,request);const edgeAnswer=await callWorkersAI(env,message);if(edgeAnswer)return json({ok:true,answer:edgeAnswer,source:'pi-chat-cloudflare-ai',truth:'model-response'},200,request);const providers=[];if(env.OPENAI_API_KEY){const configured=env.PI_CHAT_MODEL;const models=[...new Set([configured,...OPENAI_MODEL_FALLBACKS].filter(Boolean))];for(const model of models)providers.push({name:`openai:${model}`,apiKey:env.OPENAI_API_KEY,model,baseUrl:'https://api.openai.com/v1'});}if(env.PI_FALLBACK_API_KEY&&env.PI_FALLBACK_API_URL&&env.PI_FALLBACK_MODEL)providers.push({name:'fallback',apiKey:env.PI_FALLBACK_API_KEY,model:env.PI_FALLBACK_MODEL,baseUrl:env.PI_FALLBACK_API_URL});let lastFailure={failure:{error:'edge_model_unavailable',status:503},provider:'cloudflare-ai'};for(const provider of providers){try{const response=await callProvider({...provider,message});if(!response.ok){lastFailure={response,failure:providerError(response),provider:provider.name};if(response.status===429||response.status>=500||response.status===404)continue;const recovered=recoveryResponse(message,request,lastFailure);return recovered||json({ok:false,error:lastFailure.failure.error},lastFailure.failure.status,request);}const body=await response.json();const answer=extractAnswer(body);if(!answer){lastFailure={failure:{error:'empty_model_response',status:502},provider:provider.name};continue;}return json({ok:true,answer,source:`pi-chat-${provider.name}`,truth:'model-response'},200,request);}catch{lastFailure={failure:{error:'chat_provider_network_error',status:503},provider:provider.name};}}const recovered=recoveryResponse(message,request,lastFailure);if(recovered)return recovered;const failure=lastFailure.failure||{error:'chat_provider_unavailable',status:503};const headers=lastFailure.response&&failure.error==='chat_provider_rate_limited'?rateLimitHeaders(lastFailure.response):{};return json({ok:false,error:failure.error},failure.status,request,headers);}};